services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=tasks
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=khadija
    ports:
      - 5432:5432

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_EVENT_LISTENERS: jboss-logging,custom-listener
    ports:
      - "9090:8080"
    command:
      - "start-dev"