gg:
  jte:
    developmentMode: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks
    username: khadija
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Khadija
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: taskmaster-client
      principle-attribute: preferred_username

server:
  port: 8081

